spring:

  datasource:
    url: jdbc:h2:tcp://localhost/~/jpashop   # 네트워크 모드
#    url: jdbc:h2:file:~/jpashop
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create  # 애플리케이션 시작 시마다 데이터베이스 스키마를 새로 생성하므로 기존 데이터를 삭제됨.
#      ddl-auto: none   # 개발 중에는 update, 프로덕션에서는 none 또는 validate
    properties:
      hibernate:
#        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100

logging:
  level:
    org.hibernate.SQL: debug

