# 기본 이미지 설정
FROM openjdk:17-jdk-alpine as build

# 애플리케이션 파일이 복사될 작업 디렉토리 생성
WORKDIR /workspace/app

# Gradle wrapper와 프로젝트 파일 복사
COPY gradlew .
COPY gradle gradle
COPY build.gradle .
COPY settings.gradle .
COPY src src

# Gradle wrapper에 실행 권한 부여
RUN chmod +x ./gradlew

# 프로젝트 빌드, 테스트 제외
RUN ./gradlew build -x test

# 빌드 결과물을 실행할 새로운 이미지
FROM openjdk:17-jdk-alpine

WORKDIR /app

# 빌드 스테이지에서 생성된 jar 파일 복사
COPY --from=build /workspace/app/build/libs/*.jar app.jar

# 컨테이너 시작 시 실행할 커맨드
ENTRYPOINT ["java","-jar","app.jar"]
